/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cnzpeqliojewvzkxsybq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuenBlcWxpb2pld3Z6a3hzeWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwNzM2NjQsImV4cCI6MjA4NDY0OTY2NH0.dj5GX2_ypGjJg21uGzUK-6nJvBAY7-RQzzcP8857RcY"